### ISSUE TITLE
Release 1.4 tasks

### ISSUE THREAD

**Issue by caguero** [osrf/vrx#254]
- [x] Sydney Regatta Centre world. pull request #253 
  - [x] Fix Issue regarding transparency of the trees
- [x] Add 2022 course elements (buoys, markers, etc.). pull request #264 
- [x] Gazebo 11 & Noetic. Pull request #247 
- [x] Build and push ROS Noetic Docker images to GitHub
  - [x] Update CI to support Gazebo 11 / ROS Noetic
- [x] Cleaning. Pull request #255 
- [x] Review tutorials (everyone, see Trello board)
- [x] Resolve issue #261 (Carlos; should be fixed by merging PR #265)
- [x] Resolve issue #258 (Carson)
- [x] Review and merge PR #263 (Carson)
- [x] Write release announcement (Michael)

**Comment by M1chaelM** [comment]
I pushed the CI image to:
```
npslearninglab/watery_robots:current
```
I didn't have permissions to push to the osrf repo. I think I used to, so could be an error on my end. Anyway, let me know if you want to move the image to another repo.

Since we are using the same test image for both VRX and Dave, I agree with Brian that we should probably maintain it in a separate git repository. When we get this set up I will add the Github action to automatically push updates, so we are using an up-to-date image for our CI. I think the image above should work for now though.
