### ISSUE TITLE
Release 1.5 tasks

### ISSUE THREAD

**Issue by caguero** [osrf/vrx#283]
### Tasks
* [x] Task 1 - Station-Keeping - updates. Issue #272 
* [x] Task 2 - Wayfinding - updates. Issue #273
* [x] Task 3 - Perception - updates. Issue #274
* [x] Task 5 - Ping localization, channel navigation and obstacle avoidance - updates. Issue #277
* [x] Verify scoring plugins of tasks 1, 2, 3 and 5. Issue #281
* [x] Task 4 - Wildlife Encounter and Avoid Issue #276
* [x] Design and implement the deliver part of the "Dock and Deliver" task. Issue #280
* [x] Task 6 - Scan-and-dock-and-deliver - updates. Issue #278
* [x] Write scoring plugin for the deliver part of the "Dock and Deliver" task. Issue #282

### Models
* [x] Create new placards and docks. Issue #275
* [x] Issue #291
* [x] Wildlife Encounter and Avoid "buoys". Issue #302 

### Documentation
* [x] Update competition documents. Issue #284.
* [x] Update Task Descriptions to add new Task 4 - Wildlife Encounter. Issue #300 
* [x] Update Task Descriptions to add "deliver" to Task 6. Issue #301 
* [x] Create a tutorial for validating a submission. Issue #286
* [ ] Create a tutorial for running the competition and evaluating a submission. Issue #287
* [x] Wiki updates. Issue #292
* [x] #299

### Infrastructure
* [x] Include RobotX 2022 elements when launching `vrx.launch`. Issue #279
* [x] Create trivial solutions for each task. Issue #285
* [x] Create some practice worlds for each task. Issue #288
* [x] Update the automatic evaluation tool. Issue #289
* [ ] Issue #295
* [x] #298
* [x] #320

### Testing
* [x] Run all tutorials before the release. Issue #293

### Video
* [x] Create highlight video. Issue #290

### Announcement
* [x] Issue #294
