### ISSUE TITLE
VRX Scoring Plugins port Meta-Issue

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#510]
This meta-issue tracks progress on porting the VRX scoring plugins and related plugins from Gazebo Classic to the new Gazebo.

## Scoring Plugins:
* [x] Base plugin: @caguero 
  * #501
  * #504 
  * #505
  * #508
* [x] Stationkeeping: @j-herman
  * #502  
* [x] Wayfinding: @M1chaelM
  * #506  
* [x] Wildlife:@j-herman / @caguero 
  * #527
  * #547 
* [x] Perception: @caguero 
  * #525 
* [x] Gymkhana: @M1chaelM 
  * #540 
* [x] Navigation: @M1chaelM  
  * #513 
* [x] ScanDock: @caguero 
  * #537
  * #541 
  * #542 
## Related plugins / dependencies
* [x] WAM-V joystick teleop @caguero
  * #503  
* [x] BallShooter @iche033 
  * #529 
* [x] Follow: @caguero 
* [x]  Acoustic pinger: @caguero 
  * #531 
* [x] LightBuoy @caguero
  * #535 
* [x] PlacardPlugin @iche033 
  * #532
