### ISSUE TITLE
2.0.0 release meta-issue

### ISSUE THREAD

**Issue by caguero** [osrf/vrx#518]
* [x] Port all plugins: #510 
* [x] #514 
* [x] #515 
* [x] #516 
* [x] #517 
* [x] Update the documentation/wiki
* [ ] ~~Update the vrx-docker scripts~~
* [x] Changelog
* [x] Tag the repository
* [x] Announcements
